/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        'primary-fixed-dim': '#B8E600',
        'on-tertiary-fixed': '#1a1c1c',
        'on-tertiary-fixed-variant': '#454747',
        'secondary-fixed-dim': '#c8c6c5',
        error: '#ffb4ab',
        'surface-container-lowest': '#0a0a0a',
        'surface-container-low': '#141414',
        'on-tertiary-container': '#9aa08c',
        'surface-variant': '#2a2a2a',
        'inverse-surface': '#e5e2e1',
        'on-secondary-fixed-variant': '#474646',
        'on-background': '#f2f2ed',
        'on-primary-container': '#1b2400',
        'on-secondary-fixed': '#1c1b1b',
        'surface-dim': '#000000',
        'on-primary-fixed': '#141a00',
        outline: '#4d4d4d',
        'surface-tint': '#ccff00',
        'error-container': '#93000a',
        'on-error': '#690005',
        'on-tertiary': '#2f3131',
        'surface-container-highest': '#333333',
        'on-error-container': '#ffdad6',
        'secondary-container': '#4a4949',
        'on-secondary': '#313030',
        background: '#000000',
        primary: '#ffffff',
        'tertiary-fixed-dim': '#c6c6c7',
        surface: '#050505',
        'tertiary-fixed': '#e2e2e2',
        'tertiary-container': '#e2e2e2',
        'primary-fixed': '#ccff00',
        'primary-container': '#ccff00',
        'on-secondary-container': '#bab8b7',
        'surface-container-high': '#1e1e1e',
        'on-primary': '#141a00',
        'outline-variant': 'rgba(255,255,255,0.12)',
        'surface-bright': '#333333',
        tertiary: '#ffffff',
        'on-primary-fixed-variant': '#2e3a00',
        secondary: '#c8c6c5',
        'surface-container': '#161616',
        'on-surface': '#f2f2ed',
        'secondary-fixed': '#e5e2e1',
        'inverse-primary': '#4d5900',
        'on-surface-variant': '#a3a89a',
        'inverse-on-surface': '#303030',
        volt: '#ccff00',
      },
      borderRadius: {
        sm: '0.5rem',
        DEFAULT: '1rem',
        lg: '2rem',
        xl: '3rem',
        full: '9999px',
      },
      spacing: {
        base: '8px',
        xs: '4px',
        sm: '12px',
        md: '24px',
        lg: '48px',
        xl: '80px',
        gutter: '24px',
      },
      maxWidth: {
        'container-max': '1440px',
      },
      fontFamily: {
        'body-md': ['"Hanken Grotesk"', 'sans-serif'],
        'body-lg': ['"Hanken Grotesk"', 'sans-serif'],
        'headline-md': ['"Anybody"', 'sans-serif'],
        'headline-lg': ['"Anybody"', 'sans-serif'],
        'headline-lg-mobile': ['"Anybody"', 'sans-serif'],
        'display-lg': ['"Anybody"', 'sans-serif'],
        'label-sm': ['"JetBrains Mono"', 'monospace'],
      },
      fontSize: {
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'headline-lg': ['40px', { lineHeight: '48px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg-mobile': ['32px', { lineHeight: '38px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'display-lg': ['72px', { lineHeight: '76px', letterSpacing: '-0.04em', fontWeight: '800' }],
        'label-sm': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '500' }],
      },
    },
  },
  plugins: [],
}
